export enum ColumnTypes {
    TEXT = "TEXT",
    IMAGE = "IMAGE",
    RATING = "RATING",
    BADGE_TAG = "BADGE_TAG",
    USER = "USER",
    ICON = "ICON",
    LINK = "LINK",
    TEXT_WITH_IMAGE = "TEXT_WITH_IMAGE",
    LINK_WITH_IMAGE = "LINK_WITH_IMAGE",
    BUTTON = "BUTTON",
    BUTTON_WITH_ICON = "BUTTON_WITH_ICON",
    PROGRESS_BAR = "PROGRESS_BAR",
    RADIO_BUTTON = "RADIO_BUTTON",
    TOGGLE = "TOGGLE",
    CHECKBOX = "CHECKBOX",
    CUSTOM = "CUSTOM"
}